version: '3.8'
services:
  tensorflow:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/tf/project
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    networks:
      - jupyter
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root
    working_dir: /tf/project
    runtime: nvidia
networks:
  jupyter:
    driver: bridge
